project:
  type: website
  output-dir: docs

website:
  title: Hello!
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    - text: "Topic 1"
      href: computations.qmd
    # - text: "Topic 2"
    #   href: reactors.qmd

# execute:
#   freeze: auto