project:
  type: website
  output-dir: docs

website:
  title: Hello!
  navbar:
    left:
    # - href: index.qmd
    - text: "Home"
    href: computations.qmd
    - text: "Topic 2"
    href: reactors.qmd

# execute:
#   freeze: auto