project:
  type: website
  output-dir: docs

execute:
  cache: false
  enabled: true

website:
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    - text: "Process Control & Simulation"
      href: control-basics.qmd

  sidebar:
    contents:
      - control-basics.qmd
      - control-plotting.qmd
      
format:
  html:
    page-navigation: true
    fig-align: center
    fig-height: 5
    fig-width: 5.5
    css: styles.css