project:
  type: website
  output-dir: docs

website:
  title: Hello!
  navbar:
    left:
    # - href: index.qmd
      text: Home
    - computations.qmd
    - reactors.qmd

# execute:
#   freeze: auto