project:
  type: website
  output-dir: docs

execute:
  cache: false
  enabled: true

website:
  navbar:
    left:
    - text: "Home"
      href: index.qmd
    - text: "Process Control & Simulation"
      href: controls.qmd
      
format:
  html:
    page-navigation: true
    # - text: "Topic 2"
    #   href: reactors.qmd